sudo: required
services:
  - docker

before_install:
  - docker build -t michaelschaidnagel/react-test -f ./client/Dockerfile.dev ./clients

script:
  - docker run michaelschaidnagel/react-test npm test -- ---coverage

after_success:
  - docker build -t michaelschaidnagel/multi-client ./client
  - docker build -t michaelschaidnagel/multi-nginx ./nginx
  - docker build -t michaelschaidnagel/multi-server ./server
  - docker build -t michaelschaidnagel/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push to docker hub
  - docker push michaelschaidnagel/multi-client
  - docker push michaelschaidnagel/multi-nginx
  - docker push michaelschaidnagel/multi-server
  - docker push michaelschaidnagel/multi-worker